title:              "Project HexMap"
tagline:             Weekly Updates for Project HexMap
description:         Weekly Updates for Project HexMap
baseurl:            #"/Project_HexMap"
url:                #"https://ritoban123.github.io/"
github:
  url: #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Ritoban Roy-Chowdhury"
  email:             "ritobanrc@gmail.com"
navigation:
- title: Posts
  url: /posts
paginate: 5



theme: jekyll-theme-cayman
